apiVersion: batch/v1
kind: Job
metadata:
  name: my-batch-job
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: batch-task
          image: busybox
          command: ["echo", "Hello, World"]
      restartPolicy: OnFailure
      dnsPolicy: ClusterFirst
