apiVersion: v1
kind: Pod
metadata:
  name: project-01-pod-name
  labels:
    name: project-01-label
spec:
  containers:
    - name: project-01-container
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
