apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-web-statefulset
  namespace: default
spec:
  selector:
    matchLabels:
      app: web # has to match .spec.template.metadata.labels
  serviceName: "web-service"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: web # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: web
          image: nginx:latest
          ports:
            - containerPort: 80
              name: web
