pipeline{
    agent any

    parameters{
        string(name: 'DEPLOY_ENV', defaultValue: 'staging', description: 'Deployment Environment')
        booleanParam(name: 'SKIP_TESTS', defaultValue: false, description: 'Skip running tests')
    }
    stages{
        stage("Build"){
            steps{
                echo "Building for environment: ${params.DEPLOY_ENV}"
                sh 'npm run build'
            }
        }
        stage('Test'){
            when{
                expression {return !params.SKIP_TESTS}
            }
            steps{
                echo 'Running tests...'
                sh 'npm run test'
            }
        }
        stage('Deploy'){
            steps{
                echo "Deploying to ${params.DEPLOY_ENV} environment..."
                // Deployment commands here
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}