---
- name: Check if NGINX components are installed
  shell: dpkg -l | grep "{{ item }}"
  register: result
  ignore_errors: yes
  loop:
    - nginx-light
    - nginx-common
    - libnginx-mod-http-echo

- name: Display NGINX check results
  debug:
    var: result.stdout

- name: Uninstall NGINX components
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  loop:
    - nginx-light
    - nginx-common
    - libnginx-mod-http-echo

- name: Install NGINX components
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nginx-light
    - nginx-common
    - libnginx-mod-http-echo

- name: Deploy NGINX config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default

- name: Check if NGINX is running on port 80
  shell: curl -s localhost
  register: result
  ignore_errors: yes

- name: Display NGINX status
  debug:
    var: result.stdout
